version: "3.9"
services:
  mysql:
    image: mysql
    container_name: roomie_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: peterkyle01
      MYSQL_PASSWORD: mysql_pwd
      MYSQL_ROOT_PASSWORD: root_pwd
      MYSQL_DATABASE: roomieDB
    volumes:
      - mysql_data:/var/lib/mysql
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    container_name: phpMyAdmin
    ports:
      - "5400:80"
    environment:
      PMA_HOST: mysql
volumes:
  mysql_data:
